dist: xenial

language: go

go:
  - 1.11.x
  - 1.12.x

env:
  global:
    - GO111MODULE=on
    - GOFLAGS="-mod=readonly"

install:
  - make dependencies

before_script:
  - docker-compose up -d postgres

script:
  - make test-coverage
  # make codecov
  # uncomment when source{d} has more private repository credits at codecov.io

stages:
  - style
  - test
  - name: deploy
    # require any tag name
    if: tag =~ .*

matrix:
  fast_finish: true
  include:
    - stage: style
      go: 1.12.x
      addons:
        apt:
          packages:
            - python3
            - python3-pip
      before_install:
        - pip --version
      install:
        - make install-dev-deps
      before_script: skip
      script:
        - make check-style check-generate
    - stage: deploy
      go: 1.12.x
      install: skip
      before_script: skip
      script:
        - make packages
      deploy:
        provider: releases
        file_glob: true
        api_key:
          secure: $GITHUB_TOKEN
        file: build/*.tar.gz
        skip_cleanup: true
        on:
          tags: true

notifications:
  email: false
