dist: bionic

language: go

go:
  - 1.12.x
  - 1.13.x

services:
  - docker

env:
  global:
    - GO111MODULE=on

install:
  - travis_retry make dependencies

script:
  - make test-coverage
  - make codecov

stages:
  - style
  - test
  - docker-test
  - name: deploy
    # require any tag name
    if: tag =~ .*

matrix:
  fast_finish: true
  include:
    - stage: style
      go: 1.13.x
      addons:
        apt:
          packages:
            - python3
            - python3-pip
      install:
        - make install-dev-deps
      script:
        - make check-style check-generate
    - stage: test
      language: python
      python: 3.7
      addons:
        apt:
          packages:
            - libsnappy-dev
      install:
        - pip3 install -r ./parquet2sql/requirements.txt
      before_script:
        - docker run -d --name postgres --network=host -e POSTGRES_DB=superset -e POSTGRES_USER=superset -e POSTGRES_PASSWORD=superset postgres:10-alpine 
        - sleep 5
      script:
        - python3 -m unittest discover ./parquet2sql
      after_script:
        - docker rm -f postgres
    - stage: docker-test
      go: 1.13.x
      install: skip
      script:
        - make docker-test
    - stage: deploy
      go: 1.13.x
      install: skip
      script:
        - make packages
      deploy:
        provider: releases
        file_glob: true
        api_key:
          secure: $GITHUB_TOKEN
        file: build/*.tar.gz
        skip_cleanup: true
        on:
          tags: true
    - name: "Push image to Docker Hub"
      python: 3.6
      stage: deploy
      script:
        - DOCKER_PUSH_LATEST=true make docker-push

notifications:
  email: false
