version: '3.4'
services:
  gitbase:
    image: mysql:8.0.17
    container_name: im_gitbase
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./tests:/tests"
  postgres:
    image: postgres:10-alpine
    container_name: im_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
